name: bloc_practice
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.24.0
  http: ^0.12.1
  image_gallery_saver: ^1.2.2
  permission_handler: ^5.0.0+hotfix.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    
  uses-material-design: true